name: Deploy to Render

on:
  push:
    branches:
      - main  # deploy only when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"  # or whatever version your app uses

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run basic syntax test
        run: python -m py_compile $(find . -name "*.py")

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST "https://api.render.com/v1/services/${SERVICE_ID}/deploys" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${RENDER_API_KEY}" \
          -d ''
